# Generated by Django 5.2.4 on 2025-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeederExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('seeder_name', models.CharField(max_length=100)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('data_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Seeder Execution',
                'verbose_name_plural': 'Seeder Executions',
                'unique_together': {('app_label', 'seeder_name')},
            },
        ),
    ]
