# Generated by Django 5.2.4 on 2025-11-02 13:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado')], default='pending', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_contratante', to='authentication.customeruser')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_prestador', to='authentication.customeruser')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.service')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_data', models.JSONField()),
                ('evento_tipo', models.CharField(max_length=50)),
                ('processado', models.BooleanField(default=False)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Webhook de Pagamento',
                'verbose_name_plural': 'Webhooks de Pagamento',
                'ordering': ['-data_recebimento'],
            },
        ),
    ]
