# Generated by Django 5.2.4 on 2025-11-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payout_failed_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_missing_info_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='valor_plataforma',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comissão da plataforma (7% por padrão).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='valor_prestador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor líquido destinado ao prestador após comissão.', max_digits=10),
        ),
    ]
