# Generated by Django 5.2.4 on 2025-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=40, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Universidade',
                'verbose_name_plural': 'Universidades',
                'ordering': ['nome'],
            },
        ),
    ]
