# Generated by Django 5.2.4 on 2025-07-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('universitario', 'Universitário'), ('publico_externo', 'Público Externo')], max_length=20)),
                ('ano_formatura', models.IntegerField(blank=True, null=True)),
                ('contato', models.CharField(blank=True, help_text='Contato para comunicação (WhatsApp, Instagram, telefone, etc.)', max_length=50, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.curso')),
                ('universidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.universidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
