# Generated by Django 5.2.4 on 2025-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='mp_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
