# Generated by Django 5.2.4 on 2025-11-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customeruser_payout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='preferred_payout_method',
            field=models.CharField(choices=[('pix', 'PIX'), ('bank_transfer', 'Transferência Bancária')], default='pix', max_length=20),
        ),
    ]
