# Generated by Django 5.2.4 on 2025-11-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customeruser_preferred_payout_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='mp_refresh_token',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='mp_user_id',
        ),
    ]
