# Generated by Django 5.2.4 on 2025-08-29 23:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('participantes', models.ManyToManyField(related_name='salas_chat', to='authentication.customeruser')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_chat', to='services.service')),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('tipo_mensagem', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Arquivo')], default='text', max_length=10)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='authentication.customeruser')),
                ('sala_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['enviado_em'],
            },
        ),
    ]
