# Generated by Django 5.2.4 on 2025-08-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='participantes',
            field=models.ManyToManyField(related_name='salas_chat', to='authentication.customeruser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='authentication.customeruser'),
        ),
    ]
